before_install:
  - sudo apt-get update -y
  - chmod +x build.sh
  
language: node_js
node_js:
  - "node"

cache: npm

before_script:
  - sudo apt-get install -y ruby sass 
  - npm install grunt-cli -g

script: ./build.sh

deploy:
  provider: releases
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  file: dist
  on:
    tags: true

deploy:
  provider: npm
  email: "667@onezerohosting.com"
  api_key: $NPM_TOKEN
  skip_cleanup: true
